### ISSUE TITLE
[request] is there any chance you'd be willing to open-source your app: "Screen Mirror" (com.ajungg.screenmirror)

### ISSUE THREAD

**Issue by warren-bank** [ajungg/ajungg.github.io#1]
I just found it.. and it works _really_ well. Very impressive for an APK that's only 167 KB.

In the past, I tried to write something similar.. but exposed the video stream with an RTSP server. It worked.. but not nearly as well as yours. I'd be curious to see how you made yours work so well.

**Comment by warren-bank** [comment]
I just found [another app](https://github.com/dkrivoruchko/ScreenStream) that's very similar.. serves a motion jpg (mjpeg).. and also works very nicely. So.. I'll just look at its code. Sorry to bother you.

**Comment by ajungg** [comment]
Funny that you reached out, the app is removed from Google since 3 years or so and the Version you have should be my last beta Version. 

The technique i used is actually VERY simple. I start a Http-Server using nanohttpd, host a JavaScript Client that connects via WebSockets. The Server (the Android App) is then Pumping raw image frames using the ScreenCapture API. The Format depending on what you set in the Settings. 

The JavaScript App also has a VP8 decoder included (compiled via emscripten) but tbh the raw JPEG frames work much better, the Video Quality of VP8 is not that good. 

I also had H264 decoder, but removed it because of licensing concerns and used the NativeClient decoder of Google Chrome instead. Works okayish, but has its bugs. 

So the most simple Implementation (ScreenCapture API -> Encode JPEG -> WebSockets -> Decode in JavaScript) works the best. What the App currently can not handle is starved network situatations, because WebSockets uses TCP/IP instead of UDP. You may have better results using WebRTC, but that way more complicated.

**Comment by warren-bank** [comment]
Really appreciate the thoughtful response. Your approach certainly works well.

The use-case I have in mind.. is to fork [DroidPlay](https://github.com/tutikka/DroidPlay) and add support for screen mirroring to AirPlay v1 receivers.. which don't officially exist any longer. However, many years ago.. the AirPlay v1 spec was backwards engineered.. and several open-source projects were built to this unofficial spec; so though they don't work with Apple products any longer.. they are compatible with each other.

One such app is a hobby project of mine.. [ExoAirPlayer](https://github.com/warren-bank/Android-ExoPlayer-AirPlay-Receiver).. which only used the AirPlay v1 HTTP API as a starting point.. and significantly extended it.. but retains compatability with this (small) ecosystem.

There is already a [desktop mirroring app](https://github.com/zeppelsoftware/airplay) that works nicely. And though I don't intend to spend more than an afternoon on implementing this.. it would be nice to have similar functionality for Android.. and adding it to an existing AirPlay v1 client.. [DroidPlay](https://github.com/tutikka/DroidPlay) in particular.. seems like the simplest way to do so.
